language: go
dist: bionic
go:
- 1.15
before_install:
- sudo add-apt-repository universe
- sudo apt -y update
- curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
- sudo apt -y install sassc nodejs
- npm install clean-css-cli sass-lint -g
- sass-lint -v -c .sass-lint.yml ./assets/sass/*.sass
install:
- make
script:
- "./scripts/check_working.sh"
before_deploy:
- make buildall VER="$(cat VERSION)"
deploy:
  provider: releases
  api_key:
    secure: Z60rzyqdwZc5rJO0F7LhSrtAELQN81fE0OfQrWmdeusKD+8lhMQD2bgIlsJ1cUGrWhZVgHAtVC3M/6G1sGt2AAqMiKzGn4r8pUQa+RCnk/DRvQTPy5r+1UoR+1NFbzsZTWN9kDYk2lNpw+wUG0niuLLongjOWYHjcorQSuVfR+52WKPPwoX+jscy3ZXxsZ3M0HyfbbuK40Wu+t8MdNNVOGz0MnZcmeSew7NW9kJCQyMNepw0gNdne9ws1f3p+Tq0Xwiu2jzvBBMbMiQ6Y5ppgtUE4inIkoLp5sn1e5P8pTOyXc+NZmZxkgG1cB2pTb0lUPQYJJmiDJdl/5klpzd54/uNEbqZ1ebMCQxWf4cniehS6/8wG3RlIUsAfSGO8JDGFnyr3pjb61NDaF+I2pheRlsUU1Zf1nbJ3GWwTYZmEzHrKeLsIlSbwo59NqGegj5YAw/wkj7s+uKOVRLY/O+2x6LEyI5fARvyg4eVv7eZGy4GGjSDGSOxbdckbgl3BRwTOWQcpEC8joYPcyhuFA5IRswX0tVsoVZBx80oP8lbMrNFtl7be3Rb/a2ZrwDmkJ3Np69TkGbnXiB7piXWeTuPuVz5FzpRVUkP7EpfrDdtqFYJHosnYNbSTFpE1hg++vHnT/R02+tgTAJzgD+UofxkeFZaCHS1x/z/3kC9Twyfh2g=
  file_glob: true
  file:
  - gomd-*-darwin-amd64.tgz
  - gomd-*-linux-amd64.tgz
  - gomd-*-windows-amd64.tgz
  on:
    repo: wojciechkepka/gomd
    tags: true
  skip_cleanup: 'true'
