language: go
dist: bionic
go:
- 1.15
before_install:
- sudo add-apt-repository universe
- sudo apt -y update
- curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
- sudo apt -y install sassc nodejs
- npm install clean-css-cli sass-lint -g
- sass-lint -v -c .sass-lint.yml ./assets/sass/*.sass
install:
- make
script:
- "./scripts/check_working.sh"
before_deploy:
- make buildall VER="$(cat VERSION)"
deploy:
  provider: releases
  api_key:
    secure: JVtpSU6L3pWn21mWvmvyFJQcNm36HsVILKbPZ5YFj3boZTxrhMeGC+LC+AtUMVeil5XffkGwurJuJexM2N8imCtJ/IUL2lOtJx11PF8++f5/QWeAvlE1e20HaMgaHI0b1cHRxGNJsi5bg86wZD1gx8cjq1Vg1rCHAbA5vh01Y685NSVx5wHsMzYViITka/E1W0IPB/wv7PbEfu/SfNJBP07zcvG0cYdPjBJn+dmex95Rnc0O/ZUUKRsZU1l0VmZhqy6x3ILyuc9N05vPWd2C+QsBc94gE3Jj8OiUxkdvg6cn100AnOorbaGEbQgmJmfVG6LGG2d6ccOeU6xqQpgRSW5jw1Vsy5A1EzdC2+229rUWwbC0LSZ3sismyt1+3+JT80jviNvVD39XABSW5UXuSuM+oq/DSnsJNqLgeI0biM2keqrgKZxDz33dP9RPxgu8nRU6p3rXR8Q7Ou5s3TWUnOdSCgUo13q3i1YE4asRXPrd6UsWyOWzLB1mJ1a1ma6eZGiINfJpBnLYCy5Ghzovn8qFJJXRUNoRmJhwBjiDyazvESFy6HtCM4G6jtc/HDHlq76h89Tby36sNrWcnp+V68tiankZc/I/roI4m8SNajJLHxA0AXHit5xo2DlJj4kKyPQgOizW/0BK59jCITJaRlcfWnqC8qPBd1dAch7AMno=
  file_glob: true
  file:
    - "gomd-*-darwin-amd64.tgz"
    - "gomd-*-linux-amd64.tgz"
    - "gomd-*-windows-amd64.tgz"
  on:
    tags: true
  skip_cleanup: 'true'
