package assets

//This file is autogenerated from assets directory
import "fmt"

// The script
const (
    JS = `function themeChange(cb){var rq=new XMLHttpRequest;if(cb.checked){rq.open("GET","/theme/light",true)}else{rq.open("GET","/theme/dark",true)}rq.onreadystatechange=reload;rq.send()}function codeHlChange(a_theme){var rq=new XMLHttpRequest;rq.open("GET","/theme/"+a_theme.textContent,true);rq.onreadystatechange=reload;rq.send()}function reload(){location.reload()}`
)

//ReloadJs returns js responsible for a websocket reloading a page
func ReloadJs(bindAddr string) string {
    	return fmt.Sprintf(`function changeNavNotify(state){var rq=new XMLHttpRequest;if(state.includes("open")){rq.open("GET","/sidebar/open",true)}else if(state.includes("close")){rq.open("GET","/sidebar/close",true)}rq.send()}function openNav(){document.getElementsByClassName("sidebar")[0].style.width="250px";document.getElementsByClassName("main")[0].style.marginLeft="250px";changeNavNotify("open")}function closeNav(){document.getElementsByClassName("sidebar")[0].style.width="0";document.getElementsByClassName("main")[0].style.marginLeft="0";changeNavNotify("close")}function tryConnectToReload(address){var conn=new WebSocket(address);conn.onclose=function(){setTimeout(function(){tryConnectToReload(address)},2e3)};conn.onmessage=function(evt){location.reload()}}function checkSidebar(){var rq=new XMLHttpRequest;rq.open("GET","/sidebar/check",true);rq.send();rq.onreadystatechange=function(){if(rq.readyState===XMLHttpRequest.DONE){var status=rq.status;if(status===0||status>=200&&status<400){if(rq.responseText.includes("open")){openNav()}else if(rq.responseText.includes("close")){closeNav()}}}}}try{if(window["WebSocket"]){try{tryConnectToReload("ws://%v/reload")}catch(ex){tryConnectToReload("wss://%v/reload")}}else{console.log("Your browser does not support WebSockets, cannot connect to the Reload service.")}}catch(ex){console.error("Exception during connecting to Reload:",ex)}document.addEventListener("DOMContentLoaded",checkSidebar());`, bindAddr, bindAddr)
}
